# Generated by Django 4.0 on 2022-01-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_snippets_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='snippets',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
