# Generated by Django 4.0 on 2022-01-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_tags_updated_at_snippets_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippets',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
